### ISSUE TITLE
能否添加自动语音转文字

### ISSUE THREAD

**Issue by ciaoly** [ModerRAS/TelegramSearchBot#17]
QQ和微信都支持在群里将语音转换成文字，现在还可以在发送时即可转文字，从这一点上看telegram还是不如QQ和微信的。

有些场景下打字不如语音输入方便，例如走路的时候。由于gboard那个垃圾的语音识别实在是不堪，所以能否利用机器人和国内的语音SDK接口，实现语音转文字的功能呢？

**Comment by ModerRAS** [comment]
不考虑接国内的接口，不过可以期待一下接入Whisper，本地跑就完事了

**Comment by ModerRAS** [comment]
已实现，参考Commit f6c138b476f6645e099a65251d2ee748bff9a45b
