### ISSUE TITLE
能否添加自动二维码识别功能？

### ISSUE THREAD

**Issue by ciaoly** [ModerRAS/TelegramSearchBot#18]
QQ、支付宝和微信都支持聊天界面长按图片自动识别二维码功能啦，telegram在这一点上落后啦。能不能添加一个二维码自动识别的功能？或者用指令触发识别也行哇

**Comment by ModerRAS** [comment]
已经实现了，查看https://github.com/ModerRAS/TelegramSearchBot/commit/04fb26bbc2f62bcd5117aa31227adccef65d1045t 就可以了
